version: "3"

services:
  rest-jwt-auth-server:
    container_name: rest-jwt-auth-server
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - 3000:3000
    volumes:
      - .:/app

